'''
Problem 2:
    Each new term in the Fibonacci sequence is generated by adding the previous
    two terms. By starting with 1 and 2, the first 10 terms will be:

        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed 
    four million, find the sum of the even-valued terms.

Answer:
    4613732
'''

tmp  = 0
int1 = 0
int2 = 1

solution = 0

while(int2 < 4000000):
    if(int2 % 2 == 0):
        solution += int2
    tmp = int1 + int2
    int1 = int2
    int2 = tmp
    
print(solution)